export const automaticWeatherStation = [
    {"automaticWeatherStationId": "RF001", "automaticWeatherStation": "Lau Fau Shan", "district": "Yuen Long", "region": "New Territories"},
    {"automaticWeatherStationId": "RF002", "automaticWeatherStation": "Wetland Park", "district": "Yuen Long", "region": "New Territories"},
    {"automaticWeatherStationId": "N12", "automaticWeatherStation": "Shui Pin Wai", "district": "Yuen Long", "region": "New Territories"},
    {"automaticWeatherStationId": "RF003", "automaticWeatherStation": "Shek Kong", "district": "Yuen Long", "region": "New Territories"},
    {"automaticWeatherStationId": "RF004", "automaticWeatherStation": "Tai Mei Tuk", "district": "Tai Po", "region": "New Territoriesp "},
    {"automaticWeatherStationId": "RF005", "automaticWeatherStation": "Tai Po Market", "district": "Tai Po", "region": "New Territories"},
    {"automaticWeatherStationId": "RF006", "automaticWeatherStation": "Pak Tam Chung", "district": "Sai Kung", "region": "New Territories"},
    {"automaticWeatherStationId": "RF007", "automaticWeatherStation": "Kau Sai Chau", "district": "Sai Kung", "region": "New Territories"},
    {"automaticWeatherStationId": "N15", "automaticWeatherStation": "Sai Kung", "district": "Sai Kung", "region": "New Territories"},
    {"automaticWeatherStationId": "RF008", "automaticWeatherStation": "Tseung Kwan O", "district": "Sai Kung", "region": "New Territories"},
    {"automaticWeatherStationId": "RF009", "automaticWeatherStation": "Clear Water Bay", "district": "Sai Kung", "region": "New Territories"},
    {"automaticWeatherStationId": "RF010", "automaticWeatherStation": "Waglan Island", "district": "Islands", "region": "New Territories"},
    {"automaticWeatherStationId": "RF011", "automaticWeatherStation": "Cheung Chau", "district": "Islands", "region": "New Territories"},
    {"automaticWeatherStationId": "RF012", "automaticWeatherStation": "Peng Chau", "district": "Islands", "region": "New Territories"},
    {"automaticWeatherStationId": "RF013", "automaticWeatherStation": "Ngong Ping", "district": "Islands", "region": "New Territories"},
    {"automaticWeatherStationId": "RF014", "automaticWeatherStation": "Hong Kong International Airport", "district": "Islands", "region": "New Territories"},
    {"automaticWeatherStationId": "RF015", "automaticWeatherStation": "Ta Kwu Ling", "district": "North", "region": "New Territories"},
    {"automaticWeatherStationId": "RF016", "automaticWeatherStation": "Sheung Shui", "district": "North", "region": "New Territories"},
    {"automaticWeatherStationId": "RF017", "automaticWeatherStation": "Tai Lung", "district": "North", "region": "New Territories"},
    {"automaticWeatherStationId": "RF018", "automaticWeatherStation": "Tsuen Wan Ho Koon", "district": "Tsuen Wan", "region": "New Territories"},
    {"automaticWeatherStationId": "RF019", "automaticWeatherStation": "Tuen Mun", "district": "Tuen Mun", "region": "New Territories"},
    {"automaticWeatherStationId": "RF020", "automaticWeatherStation": "Sha Tin", "district": "Sha Tin", "region": "New Territories"},
    {"automaticWeatherStationId": "RF021", "automaticWeatherStation": "Cheung Ching", "district": "Kwai Tsing", "region": "New Territories"},
    {"automaticWeatherStationId": "RF022", "automaticWeatherStation": "Sham Shui Po", "district": "Sham Shui Po", "region": "Kowloon"},
    {"automaticWeatherStationId": "RF023", "automaticWeatherStation": "Hong Kong Observatory", "district": "Yau Tsim Mong", "region": "Kowloon"},
    {"automaticWeatherStationId": "RF024", "automaticWeatherStation": "King’s Park", "district": "Yau Tsim Mong", "region": "Kowloon"},
    {"automaticWeatherStationId": "K02", "automaticWeatherStation": "Broadcast Drive", "district": "Kowloon City", "region": "Kowloon"},
    {"automaticWeatherStationId": "RF025", "automaticWeatherStation": "Kai Tak", "district": "Kowloon City", "region": "Kowloon"},
    {"automaticWeatherStationId": "K09", "automaticWeatherStation": "San Po Kong", "district": "Wong Tai Sin", "region": "Kowloon"},
    {"automaticWeatherStationId": "K03", "automaticWeatherStation": "Kwun Tong", "district": "Kwun Tong", "region": "Kowloon"},
    {"automaticWeatherStationId": "RF026", "automaticWeatherStation": "Shau Kei Wan", "district": "Eastern", "region": "Hong Kong Island"},
    {"automaticWeatherStationId": "RF027", "automaticWeatherStation": "Happy Valley", "district": "Southern", "region": "Hong Kong Island"},
    {"automaticWeatherStationId": "RF028", "automaticWeatherStation": "The Peak", "district": "Central and Western", "region": "Hong Kong Island"},
    {"automaticWeatherStationId": "H17", "automaticWeatherStation": "Magazine Gap", "district": "Central and Western", "region": "Hong Kong Island"},
    {"automaticWeatherStationId": "H15", "automaticWeatherStation": "Stanley", "district": "Southern", "region": "Hong Kong Island"},
    {"automaticWeatherStationId": "H24", "automaticWeatherStation": "Wong Chuk Hang", "district": "Southern", "region": "Hong Kong Island"},
]